/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/Ginh3MzVjZI
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { IBM_Plex_Sans } from 'next/font/google'
import { Libre_Franklin } from 'next/font/google'

ibm_plex_sans({
  subsets: ['latin'],
  display: 'swap',
})

libre_franklin({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import Link from "next/link"
import { Input } from "@/components/ui/input"
import { Textarea } from "@/components/ui/textarea"
import { Button } from "@/components/ui/button"
import { Navbar } from "./view/navbar"

export function FrontComponent() {
  return (
    <div className="flex flex-col min-h-[100dvh]">

      <Navbar />

      <main className="flex-1">
        <section id="hero" className="w-full py-12 flex justify-center items-center md:py-24 lg:py-32">
          <div className="container px-4 md:px-6">
            <div className="grid gap-6 lg:grid-cols-[1fr_400px] lg:gap-12 xl:grid-cols-[1fr_600px]">
              <div className="flex flex-col justify-center space-y-4">
                <div className="space-y-2">
                  <h1 className="text-3xl font-bold tracking-tighter sm:text-5xl xl:text-6xl/none">Christophe CHHOR</h1>
                  <p className="max-w-[600px] text-muted-foreground md:text-xl">
                    Software Engineering Student at Epitech Paris
                  </p>
                </div>
                <div className="flex flex-col gap-2 min-[400px]:flex-row">
                  <Link
                    href=""
                    className="inline-flex h-10 items-center justify-center rounded-md bg-primary px-8 text-sm font-medium text-primary-foreground shadow transition-colors hover:bg-primary/90 focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-ring disabled:pointer-events-none disabled:opacity-50"
                    prefetch={false}
                  >
                    Get in Touch
                  </Link>
                </div>
              </div>
              <img
                src="/Christophe.jpg"
                width="550"
                height="550"
                alt="Hero"
                className="mx-auto aspect-square overflow-hidden rounded-xl object-cover sm:w-full lg:order-last"
              />
            </div>
          </div>
        </section>

        <section id="projects" className="w-full py-12 flex justify-center items-center md:py-24 lg:py-32 bg-muted ">
          <div className="container px-4 md:px-6 w-full">
            <div className="flex flex-col items-center justify-center space-y-4 text-center">
              <div className="space-y-2">
                <h2 className="text-3xl font-bold tracking-tighter sm:text-5xl">My Projects</h2>
                <p className="max-w-[900px] text-muted-foreground md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed">
                  {/* eslint-disable-next-line react/no-unescaped-entities */}
                  Check out some of the web applications I've built to showcase my skills.
                </p>
              </div>
            </div>
            <div className="w-full mx-auto grid max-w-5xl grid-cols-1 gap-6 py-12 sm:grid-cols-2 lg:grid-cols-2 lg:gap-12">
              <div className="rounded-lg border bg-background p-4">
                <img
                  src="/placeholder.svg"
                  width="550"
                  height="310"
                  alt="LeAREA"
                  className="mx-auto aspect-video overflow-hidden rounded-lg object-cover object-center"
                />
                <div className="mt-4 space-y-2">
                  <h3 className="text-xl font-bold">LeAREA</h3>
                  <p className="text-muted-foreground">
                    A school web project that aims to connect APIs and interact between them.
                  </p>
                  <div className="flex gap-2">
                    <Link
                      href="https://github.com/christophechr/LeAREA"
                      className="inline-flex h-8 items-center justify-center rounded-md border border-input bg-background px-4 text-sm font-medium shadow-sm transition-colors hover:bg-accent hover:text-accent-foreground focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-ring disabled:pointer-events-none disabled:opacity-50"
                      prefetch={false}
                    >
                      GitHub
                    </Link>
                  </div>
                </div>
              </div>

              <div className="rounded-lg border bg-background p-4">
                <img
                  src="/placeholder.svg"
                  width="550"
                  height="310"
                  alt="RTYPE"
                  className="mx-auto aspect-video overflow-hidden rounded-lg object-cover object-center"
                />
                <div className="mt-4 space-y-2">
                  <h3 className="text-xl font-bold">RTYPE</h3>
                  <p className="text-muted-foreground">
                    A web application that allows users to track their fitness goals and progress.
                  </p>
                  <div className="flex gap-2">
                    <Link
                      href="https://github.com/Codrux2200/Rtype"
                      className="inline-flex h-8 items-center justify-center rounded-md border border-input bg-background px-4 text-sm font-medium shadow-sm transition-colors hover:bg-accent hover:text-accent-foreground focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-ring disabled:pointer-events-none disabled:opacity-50"
                      prefetch={false}
                    >
                      GitHub
                    </Link>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </section>

        <section id="skills" className="w-full py-12 flex justify-center items-center md:py-24 lg:py-32">
          <div className="container px-4 md:px-6">
            <div className="flex flex-col items-center justify-center space-y-4 text-center">
              <div className="space-y-2">
                <h2 className="text-3xl font-bold tracking-tighter sm:text-5xl">My Skills</h2>
                <p className="max-w-[900px] text-muted-foreground md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed">
                  Here are some of the technologies and tools I{"'"}m proficient with.
                </p>
              </div>
            </div>
            <div className="mx-auto grid max-w-5xl grid-cols-2 gap-6 py-12 sm:grid-cols-3 lg:grid-cols-4 lg:gap-12">
              <div className="rounded-lg border bg-background p-4">
                <div className="flex items-center justify-center">
                  <CodepenIcon className="h-12 w-12" />
                </div>
                <div className="mt-4 text-center">
                  <h3 className="text-xl font-bold">React</h3>
                  <p className="text-muted-foreground">A JavaScript library for building user interfaces.</p>
                </div>
              </div>
              <div className="rounded-lg border bg-background p-4">
                <div className="flex items-center justify-center">
                  <CodepenIcon className="h-12 w-12" />
                </div>
                <div className="mt-4 text-center">
                  <h3 className="text-xl font-bold">Next.js</h3>
                  <p className="text-muted-foreground">A React framework for building server-rendered applications.</p>
                </div>
              </div>
              <div className="rounded-lg border bg-background p-4">
                <div className="flex items-center justify-center">
                  <WindIcon className="h-12 w-12" />
                </div>
                <div className="mt-4 text-center">
                  <h3 className="text-xl font-bold">Tailwind CSS</h3>
                  <p className="text-muted-foreground">
                    A utility-first CSS framework for rapidly building custom designs.
                  </p>
                </div>
              </div>
              <div className="rounded-lg border bg-background p-4">
                <div className="flex items-center justify-center">
                  <CodepenIcon className="h-12 w-12" />
                </div>
                <div className="mt-4 text-center">
                  <h3 className="text-xl font-bold">Node.js</h3>
                  <p className="text-muted-foreground">A JavaScript runtime built on Chrome{"'"}s V8 JavaScript engine.</p>
                </div>
              </div>
            </div>
          </div>
        </section>

        <section id="contact" className="w-full py-12 flex justify-center items-center md:py-24 lg:py-32 bg-muted">
          <div className="container px-4 md:px-6">
            <div className="flex flex-col items-center justify-center space-y-4 text-center">
              <div className="space-y-2">
                <h2 className="text-3xl font-bold tracking-tighter sm:text-5xl">Get in Touch</h2>
                <p className="max-w-[900px] text-muted-foreground md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed">
                  Feel free to reach out if you have any questions or would like to collaborate on a project.
                </p>
              </div>
              <div className="mx-auto w-full max-w-sm space-y-2">
                <form className="flex flex-col gap-4">
                  <Input type="text" placeholder="Name" className="max-w-lg flex-1" />
                  <Input type="email" placeholder="Email" className="max-w-lg flex-1" />
                  <Textarea placeholder="Message" className="max-w-lg flex-1" />
                  <Button type="submit" className="w-full">
                    Send Message
                  </Button>
                </form>
              </div>
            </div>
          </div>
        </section>
      </main>
      <footer className="flex flex-col gap-2 sm:flex-row py-6 w-full shrink-0 items-center px-4 md:px-6 border-t">
        <p className="text-xs text-muted-foreground">&copy; 2024 John Doe. All rights reserved.</p>

        <nav className="sm:ml-auto flex gap-4 sm:gap-6">
          <Link href="#" className="text-xs hover:underline underline-offset-4" prefetch={false}>
            Privacy Policy
          </Link>
          <Link href="#" className="text-xs hover:underline underline-offset-4" prefetch={false}>
            Terms of Service
          </Link>
        </nav>
      </footer>
    </div>
  )
}

function CodeIcon(props: React.SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <polyline points="16 18 22 12 16 6" />
      <polyline points="8 6 2 12 8 18" />
    </svg>
  )
}


function CodepenIcon(props: React.SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <polygon points="12 2 22 8.5 22 15.5 12 22 2 15.5 2 8.5 12 2" />
      <line x1="12" x2="12" y1="22" y2="15.5" />
      <polyline points="22 8.5 12 15.5 2 8.5" />
      <polyline points="2 15.5 12 8.5 22 15.5" />
      <line x1="12" x2="12" y1="2" y2="8.5" />
    </svg>
  )
}


function WindIcon(props: React.SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M17.7 7.7a2.5 2.5 0 1 1 1.8 4.3H2" />
      <path d="M9.6 4.6A2 2 0 1 1 11 8H2" />
      <path d="M12.6 19.4A2 2 0 1 0 14 16H2" />
    </svg>
  )
}
